-- TABLE
CREATE TABLE CLIENTE (
ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
NOME VARCHAR(80) NOT NULL,
EMAIL VARCHAR(40) NOT NULL,
TELEFONE INT);
CREATE TABLE sqlite_sequence(name,seq);
 
-- INDEX
 
-- TRIGGER
 
-- VIEW
 
